# Generated by Django 5.2.11 on 2026-02-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCIRequirement',
            fields=[
                ('requirement_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('requirement_text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'pci_requirements',
                'ordering': ['requirement_id'],
            },
        ),
        migrations.CreateModel(
            name='PCITestingProcedure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('procedure_id', models.CharField(max_length=30)),
                ('procedure_text', models.TextField(blank=True, default='')),
                ('reporting_instruction', models.TextField(blank=True, default='')),
                ('requirement', models.ForeignKey(db_column='requirement_id', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='app.pcirequirement')),
            ],
            options={
                'db_table': 'pci_testing_procedures',
                'ordering': ['procedure_id'],
            },
        ),
    ]
