# Generated by Django 5.2.11 on 2026-02-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='applicable_yn',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='client_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='doc_ref_file',
            field=models.FileField(blank=True, null=True, upload_to='doc_refs/'),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='doc_ref_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='evidence_ref_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence_refs/'),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='evidence_ref_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='qsa_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pcitestingprocedure',
            name='scope',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
