# Generated by Django 5.2.11 on 2026-02-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pcitestingprocedure_applicable_yn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='applicable_yn',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='client_comments',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='doc_ref_file',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='doc_ref_name',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='evidence_ref_file',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='evidence_ref_name',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='qsa_remarks',
        ),
        migrations.RemoveField(
            model_name='pcitestingprocedure',
            name='scope',
        ),
    ]
