# Generated by Django 5.2.11 on 2026-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pcitestingprocedure_applicable_yn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_data',
            fields=[
                ('client_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_data',
                'ordering': ['client_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pci_assess_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('procedure_id', models.CharField(db_column='procedure_id', max_length=30)),
                ('scope', models.CharField(blank=True, max_length=10, null=True)),
                ('applicable_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('doc_ref_name', models.TextField(blank=True, default='')),
                ('doc_ref_file', models.FileField(blank=True, null=True, upload_to='doc_refs/')),
                ('evidence_ref_name', models.TextField(blank=True, default='')),
                ('evidence_ref_file', models.FileField(blank=True, null=True, upload_to='evidence_refs/')),
                ('client_comments', models.TextField(blank=True, default='')),
                ('qsa_remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'pci_assessor_inputs',
                'ordering': ['requirement_id', 'client_id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pcirequirement',
            options={'managed': False, 'ordering': ['requirement_id']},
        ),
        migrations.AlterModelOptions(
            name='pcitestingprocedure',
            options={'managed': False, 'ordering': ['procedure_id']},
        ),
    ]
